import type { NextPage } from 'next';
import Head from 'next/head';
import Home from '../app/components/home/Home';

const HomePage: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Site protection</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Home />
        </div>
    );
}

export default HomePage
